version: 2.1

orbs:
  docker: circleci/docker@2.0.2

jobs:
  build-publish-docker-hub:
    executor: docker/machine
    parameters:
      image-name:
        type: string
        default: custom-go-pyenv
      image-tag:
        type: string
        default: latest
    steps:
      - checkout
      - docker/check:
          docker-username: DOCKER_HUB_USERNAME
          docker-password: DOCKER_HUB_ACCESS_TOKEN
      - docker/build:
          # lint Dockerfile via Dockerlint, before building
          lint-dockerfile: true
          image: $DOCKER_HUB_USERNAME/<< parameters.image-name >>
          tag: $CIRCLE_SHA1,<< parameters.image-tag >>
      - docker/push:
          image: $DOCKER_HUB_USERNAME/<< parameters.image-name >>
          tag: $CIRCLE_SHA1,<< parameters.image-tag >>
  run-with-custom-image:
    docker:
      - image: docker.io/kelvintaywlcircleci/custom-go-pyenv:latest
    steps:
      - run:
          name: inspect Pyenv
          command: |
            pyenv
            pyenv versions
            
            pyenv which python
            python --version
       - run:
          name: install Python 3.10.1
          command: |
            pyenv install 3.10.1
            pyenv global 3.10.1
            
            python --version

workflows:
  publish-image:
    jobs:
      # - build-publish-docker-hub
      - run-with-custom-image
